apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - vmsingle.yaml
  - node-exporter.yaml
  - kube-state-metrics.yaml
  - vmalert.yaml
  - grafana.yaml
  - alertmanager-ingress.yaml
  - secrets/grafana-admin.yaml
  - secrets/alertmanager-auth.yaml

configMapGenerator:
  - name: k8s-testwork-dashboards
    namespace: monitoring
    files:
      - cluster-health.json=dashboards/cluster-health.json
      - service-slo.json=dashboards/service-slo.json

generatorOptions:
  disableNameSuffixHash: true