apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: node-exporter
  namespace: kube-system
spec:
  repo: https://prometheus-community.github.io/helm-charts
  chart: prometheus-node-exporter
  version: 4.56.1
  targetNamespace: monitoring
  createNamespace: true
  valuesContent: |-
    fullnameOverride: node-exporter

    service:
      portName: metrics

    extraArgs:
      - --collector.disable-defaults
      - --collector.cpu
      - --collector.meminfo
      - --collector.loadavg

    resources:
      requests:
        cpu: 5m
        memory: 12Mi
      limits:
        cpu: 50m
        memory: 48Mi

    prometheus:
      monitor:
        enabled: false
