apiVersion: batch/v1
kind: Job
metadata:
  name: hpa-load
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never

      containers:
        - name: k6
          image: grafana/k6:latest
          args:
            - run
            - /scripts/script.js

          resources:
            requests:
              cpu: 20m
              memory: 32Mi
            limits:
              cpu: 200m
              memory: 128Mi

          volumeMounts:
            - name: script
              mountPath: /scripts

      volumes:
        - name: script
          configMap:
            name: hpa-load-k6
