apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-basic-auth
    namespace: monitoring
stringData:
    users: ENC[AES256_GCM,data:ADbyeTkmLPUqGDkHHThUspcnX5Sdq2KuaiVlizPZsd1oLHHS+JkOOv+PvC86mpUh6A43k/MA8leo1PanPyMw5sZFDA==,iv:znEneftcu4MYpCUFR97hGRiRRLn1j7H8AtVAIy/nSPw=,tag:/PI/IWBQzq2y0QkZF7LCIg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5dnNMQjJFTnRTREpQRWl3
            cHg1K0pVdHk0MlQwcmVkdWx0MHN3enZId0VRClVDcGI2T1prb3BJSzJ0eUgvYUlC
            QVBPWXFpMitMb2NvV0lHbUpTSlYvbmcKLS0tIG05bGdWbUFXQ1grZDFKdCtGNWtP
            K1BwSXNjVnUzSnk5THkxZ3c0ZW9ZQkkK72sY7wvUy0tw1aDb14dShOQF18BE/yOK
            +vpxVLDvbq1QVNpEm7kRcDoz99Ajnpf6tc+/WGll1UzvKD0XSsCxGw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vce29fflxzphf7trglqqq94hkakdqpm5jtamjvrpl6fyh9naqy0st8kdfn
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-04T12:16:02Z"
    mac: ENC[AES256_GCM,data:j+SzDpMrvUAz4uyHX4+i7YzxdU0iiQyApFwVbaali3b27Cv6p7aYohJMxzlD8hbWsbVEN4c7+OW7H3jNPvpszWCYwM9JPV/J0reKfkR7B2+4aCD+nj0UDttp0CSQOFjmMTbX0QLlAoaKC0vGMgaJz9CdVAbg4u4wv45iAbEcobw=,iv:jsA7kbnNLLS5E2MIQfkTSyGkyqeoyW6zyTWE/9jvluA=,tag:EAuHYOKMc3NQJQNSiy37nA==,type:str]
    version: 3.13.3
