apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin
    namespace: monitoring
stringData:
    GRAFANA_ADMIN_PASSWORD: ENC[AES256_GCM,data:ZAFl78J3vls+MOLBVts=,iv:/RAbxCds03K4+82274t+JXWiMSSYT2/7NBowa+kxonQ=,tag:2sLuKd3XxFbWChj2jFh9/Q==,type:str]
    GRAFANA_ADMIN_USER: ENC[AES256_GCM,data:KNOq854=,iv:dFysL3hCjVmpS/0IbvYF56qW1ggS2zamRXb00L5vA5g=,tag:DRJsRohPg0v2VCYTIzAAkg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5NTc2K2IwTDFBWFR6RlhW
            ajNGa2t2azIzTHp6UUk4NnVOYUhKSjRNQkVjCjBGS29FK1R0dzZoLzRZREJGa3ox
            ZWozdkpkOEFPZSsrM3BUUHJTOWUwbVkKLS0tIDhIMFhqNjZGc0NJRDgzQ2ZZQWdx
            SVh6alptT0ZZM05tRnh6OEJ6YTExZ2sKQwDxw0GMYTp+I+a+mDlu4hy2GOWnO6Lm
            HkdVKLm212oTNg8RylmflRg1w7IK0I4ODI3/zE4as+TNmi6+IAji9A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vce29fflxzphf7trglqqq94hkakdqpm5jtamjvrpl6fyh9naqy0st8kdfn
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-04T12:41:52Z"
    mac: ENC[AES256_GCM,data:8CAFNhVarBATbwbqRRwcnb0ZbgS8hTUGvWdXvuq3tDMrwfPXmisD0it5n4nNZLzXMu7Ke2u/sTvydhEFHd+xEd1oVBcCfR98Ke9u4KI2pzysN52zqhviAnDDxNipHGuR9XjZ/e31LCUaOiE4g9OjRoIFNP0RCpMADBFhUuvRvzs=,iv:WBSZa/VluHa5GhBztlsrAdvWKgvKb+L0YWhyR/g+uYI=,tag:d0yp+9UNV5JmuvmjmYifWg==,type:str]
    version: 3.13.3
